### ISSUE TITLE
Set up blog

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_pytorch_pathway_commons#1]
See README: https://github.com/cannin/gsoc_2023_pytorch_pathway_commons

**Comment by Favourj-bit** [comment]
I have updated readme and contributors.csv file. Am I be required to create a pull request for each file I update?

**Comment by Favourj-bit** [comment]
For the documents in reports, I noticed that it is Yoshitaka reports, I wanted to confirm if you wanted me to remove them?

**Comment by Favourj-bit** [comment]
This is the blog I will be using: https://medium.com/@favour.ujames196

**Comment by inoue0426** [comment]
@Favourj-bit Please close the issues which you have done.
