### ISSUE TITLE
Create baseline model to compare with GNN models

### ISSUE THREAD

**Issue by inoue0426** [cannin/gsoc_2023_pytorch_pathway_commons#11]
Need to make a baseline model.
We can use automl models such as FLAML, AutoSklearn, and AutoKeras.

**Comment by Favourj-bit** [comment]
Hi @inoue0426
I don't know if you could please help expand on this task. I don't really understand what I'm supposed to do

**Comment by inoue0426** [comment]
@Favourj-bit make a baseline results using other model to compare with your GNN models

**Comment by inoue0426** [comment]
@Favourj-bit 
Reference:
https://github.com/microsoft/FLAML
https://automl.github.io/auto-sklearn/master/
https://autokeras.com/

Sample:
https://github.com/cannin/graph_neural_network_drug_response/blob/main/notebook/get_autokeras.ipynb

**Comment by cannin** [comment]
@Favourj-bit I agree with @inoue0426 that this is a good next step; reviewers of the work often ask for such comparisons.
