### ISSUE TITLE
Submit sample dataset to PyG

### ISSUE THREAD

**Issue by Favourj-bit** [cannin/gsoc_2023_pytorch_pathway_commons#12]
1. Use InMemory dataset function to wrap the dataset
2. Ensure dataset has basic PyG attributes
3. Submit pull request with dataset to PyG
4. Create detailed notebook to show how it was created

**Comment by cannin** [comment]
@Favourj-bit just talked with @inoue0426; he said that you might know how to do step 1 with InMemory yet; please learn how to do.

**Comment by Favourj-bit** [comment]
@cannin @inoue0426 
I've been able to use the function in wrapping the dataset. Should i proceed with submitting pull request of the created data?

**Comment by Favourj-bit** [comment]
No. 2.
In the function, i'm downloading the data from google drive. Do you think i should make it get downloaded from github instead?

**Comment by inoue0426** [comment]
@Favourj-bit Still the data is small, so submiting the whole data collected from a lot of diseases is better, IMO. 

For google drive, people cannot use the data on your google drive, so should use GitHub.

**Comment by Favourj-bit** [comment]
@inoue0426 
Ok, thank you. I will start work on larger datasets

**Comment by cannin** [comment]
@inoue0426 please post here links to all content you plan on submitting to PyG (data, code, description, ...) so we can review

**Comment by inoue0426** [comment]
↑ @Favourj-bit

**Comment by Favourj-bit** [comment]
Hi @cannin @inoue0426 
Here are the links to everything I want to submit to PyG based on the breast cancer dataset.

1. This is the zenodo link that contains the dataset: https://zenodo.org/record/8179187
2. https://colab.research.google.com/drive/1GgSlG9sIL312nK5wvX6_tzhFx9vYu8w1?usp=sharing

**Comment by Favourj-bit** [comment]
However, there is something I am trying to finalise with Matthias, he is the PyG guy. Going through the datasets on the PyG GitHub page, I noticed that the Python scripts for the different datasets were included there. So, I reached out to confirm this. Also, the dataset will be too large to include on GitHub directly given its size so another reason why I need to finalize with him on what I will need to make a pull request. I will inform you of the updates. I hope you could give my work reviews too before I proceed with the pull request

**Comment by Favourj-bit** [comment]
@cannin @inoue0426 
I have gotten a response from him. He confirmed my thoughts, I'm to submit the pull request including the file that downloads and processes the data while it is being hosted somewhere else.
Waiting for the go-ahead before submitting a pull request

**Comment by Favourj-bit** [comment]
He also mentioned that a Python file is the accepted format. so here is the Python file:
[Breast invasive carcinoma(brca).py.zip](https://github.com/cannin/gsoc_2023_pytorch_pathway_commons/files/12162655/Breast.invasive.carcinoma.brca.py.zip)

**Comment by cannin** [comment]
@Favourj-bit commit to this repository for review the unzipped Python file. I doubt anyone wants a pull request with zipped code. Remove the zip file.

**Comment by Favourj-bit** [comment]
Okay. I zipped it because I couldn't attach the python file under my comment, it was saying unaccepted file type. I'll commit it and inform you once it's done

**Comment by Favourj-bit** [comment]
@cannin @inoue0426 
The python file has been committed to the repository

**Comment by Favourj-bit** [comment]
@cannin @inoue0426 
<img width="725" alt="Screenshot 2023-07-31 at 18 05 35" src="https://github.com/cannin/gsoc_2023_pytorch_pathway_commons/assets/63251266/d28c11ce-9ff9-485c-bffb-1720842fcb22">
Here is the response from the PyG guy
