### ISSUE TITLE
Use underscores and lower case names

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_pytorch_pathway_commons#16]
Use underscores and lower case names

**Comment by Favourj-bit** [comment]
Done
@cannin @inoue0426 
please try out the notebook locally.
https://colab.research.google.com/drive/1YHTJgRreJnAmvs3qNkErBFc41vAwqSa9#scrollTo=LeQyrGgsqM0z

**Comment by inoue0426** [comment]
@Favourj-bit Looks good to me on M1 Mac.
Maybe you should try on windows and linux.

**Comment by Favourj-bit** [comment]
ok, my system is windows. I will try it on my jupyter notebook. I will check if i can get someone with linux to test it

**Comment by Favourj-bit** [comment]
it works on windows fine
