### ISSUE TITLE
Questions to ask PyG

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_pytorch_pathway_commons#18]
* What is the size limit for example data?
* What the size for the largest example data set?

**Comment by Favourj-bit** [comment]
I got responses from the PyG guy already. I could share it in our meeting today. But here is the screenshot of the response.
![WhatsApp Image 2023-07-13 at 11 52 08](https://github.com/cannin/gsoc_2023_pytorch_pathway_commons/assets/63251266/86a932b5-4500-4eb7-bb26-2308ee7c7c00)
