### ISSUE TITLE
What are the sizes of the BRCA and ACC Datasets

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_pytorch_pathway_commons#19]
Include the information as shown here: 
https://pytorch-geometric.readthedocs.io/en/latest/cheatsheet/data_cheatsheet.html

**Comment by inoue0426** [comment]
@Favourj-bit PyG sample data list. 
https://docs.google.com/spreadsheets/d/1pBCHNLPAEjnR8lDXaH3yDtHeiyHjLgBan8Kuc6jfpvM/edit?usp=sharing

**Comment by Favourj-bit** [comment]
@cannin @inoue0426 
https://docs.google.com/spreadsheets/d/1YvuTu72ch41sr6rEM1XjkyyLPTRQZKkYtpBME5UsfXU/edit#gid=0

Given that it is a regression task, i did not know what to put under classes

**Comment by inoue0426** [comment]
@Favourj-bit Looks good to me. Feel like over 1000 is enough as sample data. Maybe for further analysis, I want you to make a whole data model containing more diseases if possible.

**Comment by cannin** [comment]
@Favourj-bit could you make another sheet on the spreadsheet with the following information:

* cancer type
* sample count
* algorithm
* mse
* validation_split_type
* full_training_time

**Comment by Favourj-bit** [comment]
@cannin for the sample count here, should I list out the original sample size or the size gotten after preprocessing the dataset?
