### ISSUE TITLE
Make Colab notebook show you can parse cBioPortal and Pathway Commons data

### ISSUE THREAD

**Issue by cannin** [cannin/gsoc_2023_pytorch_pathway_commons#2]

**Comment by cannin** [comment]
# Datasets to Use
* Pathway Commons: https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.reactome.hgnc.sif.gz
* cBioPortal (ACC, data_clinical_patient.txt and data_mrna_seq_v2_rsem.txt): https://github.com/cBioPortal/datahub/tree/master/public/acc_tcga_pan_can_atlas_2018

**Comment by Favourj-bit** [comment]
Hi @cannin 
Is there a way of viewing the pathway commons data like how we could do for cBio's own in order to know what to expect while parsing it?
I already tried parsing the data. I used VsCode to view the data using gzip decompressor, but I want to be sure of what I'm seeing.
![image](https://github.com/cannin/gsoc_2023_pytorch_pathway_commons/assets/63251266/3cf7706c-dfab-458f-abf1-d911727b3661)

**Comment by inoue0426** [comment]
@Favourj-bit Is this what you want?
https://github.com/fujiisoup/sif_reader

**Comment by Favourj-bit** [comment]
Hi @inoue0426, not really. I have checked it out. It will help me too, thank you.

**Comment by cannin** [comment]
@Favourj-bit You should just uncompress it and read it as a table with Pandas; no need for extra libraries. What you see in your screenshot is it; a table with 3 columns.

**Comment by Favourj-bit** [comment]
oh, great. Thank you @cannin 
Yes, i will do that for the data from cBio portal

**Comment by inoue0426** [comment]
@Favourj-bit you can do like this.
![Screenshot 2023-05-16 at 13 16 30](https://github.com/cannin/gsoc_2023_pytorch_pathway_commons/assets/8393063/c99b6316-cfd0-47e2-9c8c-db228807daca)

**Comment by Favourj-bit** [comment]
@inoue0426 , i already did that in my notebook. I'm however getting some issues while trying to do that for the data from cBio portal. I came across a notebook on cBio github page to help with it sha

**Comment by Favourj-bit** [comment]
@cannin 
I came across this: https://github.com/cBioPortal/codebook/blob/main/python/intro/intro.ipynb

could I use the steps here too?

**Comment by cannin** [comment]
@Favourj-bit it is better if you download the data so the code is not dependent on an internet service, but if the code helps you plot figures then yes.

**Comment by Favourj-bit** [comment]
Okay, noted

**Comment by Favourj-bit** [comment]
@cannin I wanted to ask if i should try parsing other pathway commons and cBio datasets

**Comment by cannin** [comment]
@Favourj-bit you you need to do this before project start and provide Jupyter notebooks to show your work.
